/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentDashboardRouteImport } from './routes/student-dashboard'
import { Route as StudentRouteImport } from './routes/student'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideosIndexRouteImport } from './routes/videos.index'
import { Route as QuizzesIndexRouteImport } from './routes/quizzes.index'
import { Route as ParentIndexRouteImport } from './routes/parent.index'
import { Route as GradesIndexRouteImport } from './routes/grades.index'
import { Route as AnnouncementsIndexRouteImport } from './routes/announcements.index'
import { Route as VideosSlugRouteImport } from './routes/videos.$slug'
import { Route as QuizzesSlugRouteImport } from './routes/quizzes.$slug'
import { Route as ParentSlugRouteImport } from './routes/parent.$slug'
import { Route as CategoriesCategoryRouteImport } from './routes/categories.$category'
import { Route as AnnouncementsSlugRouteImport } from './routes/announcements.$slug'
import { Route as GradesGradeIndexRouteImport } from './routes/grades.$grade.index'
import { Route as GradesGradeLessonRouteImport } from './routes/grades.$grade.$lesson'
import { Route as GradesGradeUnitsUnitRouteImport } from './routes/grades.$grade.units.$unit'

const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student-dashboard',
  path: '/student-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIndexRoute = VideosIndexRouteImport.update({
  id: '/videos/',
  path: '/videos/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesIndexRoute = QuizzesIndexRouteImport.update({
  id: '/quizzes/',
  path: '/quizzes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentIndexRoute = ParentIndexRouteImport.update({
  id: '/parent/',
  path: '/parent/',
  getParentRoute: () => rootRouteImport,
} as any)
const GradesIndexRoute = GradesIndexRouteImport.update({
  id: '/grades/',
  path: '/grades/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsIndexRoute = AnnouncementsIndexRouteImport.update({
  id: '/announcements/',
  path: '/announcements/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosSlugRoute = VideosSlugRouteImport.update({
  id: '/videos/$slug',
  path: '/videos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesSlugRoute = QuizzesSlugRouteImport.update({
  id: '/quizzes/$slug',
  path: '/quizzes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentSlugRoute = ParentSlugRouteImport.update({
  id: '/parent/$slug',
  path: '/parent/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCategoryRoute = CategoriesCategoryRouteImport.update({
  id: '/categories/$category',
  path: '/categories/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsSlugRoute = AnnouncementsSlugRouteImport.update({
  id: '/announcements/$slug',
  path: '/announcements/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GradesGradeIndexRoute = GradesGradeIndexRouteImport.update({
  id: '/grades/$grade/',
  path: '/grades/$grade/',
  getParentRoute: () => rootRouteImport,
} as any)
const GradesGradeLessonRoute = GradesGradeLessonRouteImport.update({
  id: '/grades/$grade/$lesson',
  path: '/grades/$grade/$lesson',
  getParentRoute: () => rootRouteImport,
} as any)
const GradesGradeUnitsUnitRoute = GradesGradeUnitsUnitRouteImport.update({
  id: '/grades/$grade/units/$unit',
  path: '/grades/$grade/units/$unit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/resources': typeof ResourcesRoute
  '/student': typeof StudentRoute
  '/student-dashboard': typeof StudentDashboardRoute
  '/announcements/$slug': typeof AnnouncementsSlugRoute
  '/categories/$category': typeof CategoriesCategoryRoute
  '/parent/$slug': typeof ParentSlugRoute
  '/quizzes/$slug': typeof QuizzesSlugRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/announcements/': typeof AnnouncementsIndexRoute
  '/grades/': typeof GradesIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/quizzes/': typeof QuizzesIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/grades/$grade/$lesson': typeof GradesGradeLessonRoute
  '/grades/$grade/': typeof GradesGradeIndexRoute
  '/grades/$grade/units/$unit': typeof GradesGradeUnitsUnitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/resources': typeof ResourcesRoute
  '/student': typeof StudentRoute
  '/student-dashboard': typeof StudentDashboardRoute
  '/announcements/$slug': typeof AnnouncementsSlugRoute
  '/categories/$category': typeof CategoriesCategoryRoute
  '/parent/$slug': typeof ParentSlugRoute
  '/quizzes/$slug': typeof QuizzesSlugRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/announcements': typeof AnnouncementsIndexRoute
  '/grades': typeof GradesIndexRoute
  '/parent': typeof ParentIndexRoute
  '/quizzes': typeof QuizzesIndexRoute
  '/videos': typeof VideosIndexRoute
  '/grades/$grade/$lesson': typeof GradesGradeLessonRoute
  '/grades/$grade': typeof GradesGradeIndexRoute
  '/grades/$grade/units/$unit': typeof GradesGradeUnitsUnitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/resources': typeof ResourcesRoute
  '/student': typeof StudentRoute
  '/student-dashboard': typeof StudentDashboardRoute
  '/announcements/$slug': typeof AnnouncementsSlugRoute
  '/categories/$category': typeof CategoriesCategoryRoute
  '/parent/$slug': typeof ParentSlugRoute
  '/quizzes/$slug': typeof QuizzesSlugRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/announcements/': typeof AnnouncementsIndexRoute
  '/grades/': typeof GradesIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/quizzes/': typeof QuizzesIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/grades/$grade/$lesson': typeof GradesGradeLessonRoute
  '/grades/$grade/': typeof GradesGradeIndexRoute
  '/grades/$grade/units/$unit': typeof GradesGradeUnitsUnitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-login'
    | '/auth'
    | '/contact'
    | '/resources'
    | '/student'
    | '/student-dashboard'
    | '/announcements/$slug'
    | '/categories/$category'
    | '/parent/$slug'
    | '/quizzes/$slug'
    | '/videos/$slug'
    | '/announcements/'
    | '/grades/'
    | '/parent/'
    | '/quizzes/'
    | '/videos/'
    | '/grades/$grade/$lesson'
    | '/grades/$grade/'
    | '/grades/$grade/units/$unit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-login'
    | '/auth'
    | '/contact'
    | '/resources'
    | '/student'
    | '/student-dashboard'
    | '/announcements/$slug'
    | '/categories/$category'
    | '/parent/$slug'
    | '/quizzes/$slug'
    | '/videos/$slug'
    | '/announcements'
    | '/grades'
    | '/parent'
    | '/quizzes'
    | '/videos'
    | '/grades/$grade/$lesson'
    | '/grades/$grade'
    | '/grades/$grade/units/$unit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/admin-login'
    | '/auth'
    | '/contact'
    | '/resources'
    | '/student'
    | '/student-dashboard'
    | '/announcements/$slug'
    | '/categories/$category'
    | '/parent/$slug'
    | '/quizzes/$slug'
    | '/videos/$slug'
    | '/announcements/'
    | '/grades/'
    | '/parent/'
    | '/quizzes/'
    | '/videos/'
    | '/grades/$grade/$lesson'
    | '/grades/$grade/'
    | '/grades/$grade/units/$unit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  ResourcesRoute: typeof ResourcesRoute
  StudentRoute: typeof StudentRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  AnnouncementsSlugRoute: typeof AnnouncementsSlugRoute
  CategoriesCategoryRoute: typeof CategoriesCategoryRoute
  ParentSlugRoute: typeof ParentSlugRoute
  QuizzesSlugRoute: typeof QuizzesSlugRoute
  VideosSlugRoute: typeof VideosSlugRoute
  AnnouncementsIndexRoute: typeof AnnouncementsIndexRoute
  GradesIndexRoute: typeof GradesIndexRoute
  ParentIndexRoute: typeof ParentIndexRoute
  QuizzesIndexRoute: typeof QuizzesIndexRoute
  VideosIndexRoute: typeof VideosIndexRoute
  GradesGradeLessonRoute: typeof GradesGradeLessonRoute
  GradesGradeIndexRoute: typeof GradesGradeIndexRoute
  GradesGradeUnitsUnitRoute: typeof GradesGradeUnitsUnitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student-dashboard': {
      id: '/student-dashboard'
      path: '/student-dashboard'
      fullPath: '/student-dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/': {
      id: '/videos/'
      path: '/videos'
      fullPath: '/videos/'
      preLoaderRoute: typeof VideosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/': {
      id: '/quizzes/'
      path: '/quizzes'
      fullPath: '/quizzes/'
      preLoaderRoute: typeof QuizzesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/': {
      id: '/parent/'
      path: '/parent'
      fullPath: '/parent/'
      preLoaderRoute: typeof ParentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grades/': {
      id: '/grades/'
      path: '/grades'
      fullPath: '/grades/'
      preLoaderRoute: typeof GradesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements/': {
      id: '/announcements/'
      path: '/announcements'
      fullPath: '/announcements/'
      preLoaderRoute: typeof AnnouncementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/$slug': {
      id: '/videos/$slug'
      path: '/videos/$slug'
      fullPath: '/videos/$slug'
      preLoaderRoute: typeof VideosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/$slug': {
      id: '/quizzes/$slug'
      path: '/quizzes/$slug'
      fullPath: '/quizzes/$slug'
      preLoaderRoute: typeof QuizzesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/$slug': {
      id: '/parent/$slug'
      path: '/parent/$slug'
      fullPath: '/parent/$slug'
      preLoaderRoute: typeof ParentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$category': {
      id: '/categories/$category'
      path: '/categories/$category'
      fullPath: '/categories/$category'
      preLoaderRoute: typeof CategoriesCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements/$slug': {
      id: '/announcements/$slug'
      path: '/announcements/$slug'
      fullPath: '/announcements/$slug'
      preLoaderRoute: typeof AnnouncementsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grades/$grade/': {
      id: '/grades/$grade/'
      path: '/grades/$grade'
      fullPath: '/grades/$grade/'
      preLoaderRoute: typeof GradesGradeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grades/$grade/$lesson': {
      id: '/grades/$grade/$lesson'
      path: '/grades/$grade/$lesson'
      fullPath: '/grades/$grade/$lesson'
      preLoaderRoute: typeof GradesGradeLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grades/$grade/units/$unit': {
      id: '/grades/$grade/units/$unit'
      path: '/grades/$grade/units/$unit'
      fullPath: '/grades/$grade/units/$unit'
      preLoaderRoute: typeof GradesGradeUnitsUnitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AdminLoginRoute: AdminLoginRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  ResourcesRoute: ResourcesRoute,
  StudentRoute: StudentRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  AnnouncementsSlugRoute: AnnouncementsSlugRoute,
  CategoriesCategoryRoute: CategoriesCategoryRoute,
  ParentSlugRoute: ParentSlugRoute,
  QuizzesSlugRoute: QuizzesSlugRoute,
  VideosSlugRoute: VideosSlugRoute,
  AnnouncementsIndexRoute: AnnouncementsIndexRoute,
  GradesIndexRoute: GradesIndexRoute,
  ParentIndexRoute: ParentIndexRoute,
  QuizzesIndexRoute: QuizzesIndexRoute,
  VideosIndexRoute: VideosIndexRoute,
  GradesGradeLessonRoute: GradesGradeLessonRoute,
  GradesGradeIndexRoute: GradesGradeIndexRoute,
  GradesGradeUnitsUnitRoute: GradesGradeUnitsUnitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
