/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoLessonsRouteImport } from './routes/video-lessons'
import { Route as StudentDashboardRouteImport } from './routes/student-dashboard'
import { Route as StudentRouteImport } from './routes/student'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ResourceLibraryRouteImport } from './routes/resource-library'
import { Route as HallOfFameRouteImport } from './routes/hall-of-fame'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideosIndexRouteImport } from './routes/videos.index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as QuizzesIndexRouteImport } from './routes/quizzes.index'
import { Route as ParentIndexRouteImport } from './routes/parent.index'
import { Route as GradesIndexRouteImport } from './routes/grades.index'
import { Route as AnnouncementsIndexRouteImport } from './routes/announcements.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as VideosSlugRouteImport } from './routes/videos.$slug'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as QuizzesSlugRouteImport } from './routes/quizzes.$slug'
import { Route as ParentSettingsRouteImport } from './routes/parent.settings'
import { Route as ParentDashboardRouteImport } from './routes/parent.dashboard'
import { Route as ParentSlugRouteImport } from './routes/parent.$slug'
import { Route as CategoriesCategoryRouteImport } from './routes/categories.$category'
import { Route as AnnouncementsSlugRouteImport } from './routes/announcements.$slug'
import { Route as AdminUploadTestRouteImport } from './routes/admin/upload-test'
import { Route as GradesGradeIndexRouteImport } from './routes/grades.$grade.index'
import { Route as AdminQuizSubmissionsIndexRouteImport } from './routes/admin/quiz-submissions.index'
import { Route as AdminLessonsIndexRouteImport } from './routes/admin/lessons.index'
import { Route as AdminAnalyticsIndexRouteImport } from './routes/admin/analytics.index'
import { Route as GradesGradeLessonRouteImport } from './routes/grades.$grade.$lesson'
import { Route as GradesGradeUnitsUnitRouteImport } from './routes/grades.$grade.units.$unit'
import { Route as AdminLessonsEditLessonIdRouteImport } from './routes/admin.lessons.edit.$lessonId'

const VideoLessonsRoute = VideoLessonsRouteImport.update({
  id: '/video-lessons',
  path: '/video-lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student-dashboard',
  path: '/student-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourceLibraryRoute = ResourceLibraryRouteImport.update({
  id: '/resource-library',
  path: '/resource-library',
  getParentRoute: () => rootRouteImport,
} as any)
const HallOfFameRoute = HallOfFameRouteImport.update({
  id: '/hall-of-fame',
  path: '/hall-of-fame',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIndexRoute = VideosIndexRouteImport.update({
  id: '/videos/',
  path: '/videos/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const QuizzesIndexRoute = QuizzesIndexRouteImport.update({
  id: '/quizzes/',
  path: '/quizzes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentIndexRoute = ParentIndexRouteImport.update({
  id: '/parent/',
  path: '/parent/',
  getParentRoute: () => rootRouteImport,
} as any)
const GradesIndexRoute = GradesIndexRouteImport.update({
  id: '/grades/',
  path: '/grades/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsIndexRoute = AnnouncementsIndexRouteImport.update({
  id: '/announcements/',
  path: '/announcements/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const VideosSlugRoute = VideosSlugRouteImport.update({
  id: '/videos/$slug',
  path: '/videos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const QuizzesSlugRoute = QuizzesSlugRouteImport.update({
  id: '/quizzes/$slug',
  path: '/quizzes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentSettingsRoute = ParentSettingsRouteImport.update({
  id: '/parent/settings',
  path: '/parent/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentDashboardRoute = ParentDashboardRouteImport.update({
  id: '/parent/dashboard',
  path: '/parent/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentSlugRoute = ParentSlugRouteImport.update({
  id: '/parent/$slug',
  path: '/parent/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCategoryRoute = CategoriesCategoryRouteImport.update({
  id: '/categories/$category',
  path: '/categories/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsSlugRoute = AnnouncementsSlugRouteImport.update({
  id: '/announcements/$slug',
  path: '/announcements/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUploadTestRoute = AdminUploadTestRouteImport.update({
  id: '/upload-test',
  path: '/upload-test',
  getParentRoute: () => AdminRouteRoute,
} as any)
const GradesGradeIndexRoute = GradesGradeIndexRouteImport.update({
  id: '/grades/$grade/',
  path: '/grades/$grade/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuizSubmissionsIndexRoute =
  AdminQuizSubmissionsIndexRouteImport.update({
    id: '/quiz-submissions/',
    path: '/quiz-submissions/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminLessonsIndexRoute = AdminLessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsIndexRoute = AdminAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const GradesGradeLessonRoute = GradesGradeLessonRouteImport.update({
  id: '/grades/$grade/$lesson',
  path: '/grades/$grade/$lesson',
  getParentRoute: () => rootRouteImport,
} as any)
const GradesGradeUnitsUnitRoute = GradesGradeUnitsUnitRouteImport.update({
  id: '/grades/$grade/units/$unit',
  path: '/grades/$grade/units/$unit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLessonsEditLessonIdRoute =
  AdminLessonsEditLessonIdRouteImport.update({
    id: '/lessons/edit/$lessonId',
    path: '/lessons/edit/$lessonId',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/resource-library': typeof ResourceLibraryRoute
  '/resources': typeof ResourcesRoute
  '/student': typeof StudentRouteWithChildren
  '/student-dashboard': typeof StudentDashboardRoute
  '/video-lessons': typeof VideoLessonsRoute
  '/admin/upload-test': typeof AdminUploadTestRoute
  '/announcements/$slug': typeof AnnouncementsSlugRoute
  '/categories/$category': typeof CategoriesCategoryRoute
  '/parent/$slug': typeof ParentSlugRoute
  '/parent/dashboard': typeof ParentDashboardRoute
  '/parent/settings': typeof ParentSettingsRoute
  '/quizzes/$slug': typeof QuizzesSlugRoute
  '/student/profile': typeof StudentProfileRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/announcements/': typeof AnnouncementsIndexRoute
  '/grades/': typeof GradesIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/quizzes/': typeof QuizzesIndexRoute
  '/student/': typeof StudentIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/grades/$grade/$lesson': typeof GradesGradeLessonRoute
  '/admin/analytics/': typeof AdminAnalyticsIndexRoute
  '/admin/lessons/': typeof AdminLessonsIndexRoute
  '/admin/quiz-submissions/': typeof AdminQuizSubmissionsIndexRoute
  '/grades/$grade/': typeof GradesGradeIndexRoute
  '/admin/lessons/edit/$lessonId': typeof AdminLessonsEditLessonIdRoute
  '/grades/$grade/units/$unit': typeof GradesGradeUnitsUnitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/resource-library': typeof ResourceLibraryRoute
  '/resources': typeof ResourcesRoute
  '/student-dashboard': typeof StudentDashboardRoute
  '/video-lessons': typeof VideoLessonsRoute
  '/admin/upload-test': typeof AdminUploadTestRoute
  '/announcements/$slug': typeof AnnouncementsSlugRoute
  '/categories/$category': typeof CategoriesCategoryRoute
  '/parent/$slug': typeof ParentSlugRoute
  '/parent/dashboard': typeof ParentDashboardRoute
  '/parent/settings': typeof ParentSettingsRoute
  '/quizzes/$slug': typeof QuizzesSlugRoute
  '/student/profile': typeof StudentProfileRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/admin': typeof AdminIndexRoute
  '/announcements': typeof AnnouncementsIndexRoute
  '/grades': typeof GradesIndexRoute
  '/parent': typeof ParentIndexRoute
  '/quizzes': typeof QuizzesIndexRoute
  '/student': typeof StudentIndexRoute
  '/videos': typeof VideosIndexRoute
  '/grades/$grade/$lesson': typeof GradesGradeLessonRoute
  '/admin/analytics': typeof AdminAnalyticsIndexRoute
  '/admin/lessons': typeof AdminLessonsIndexRoute
  '/admin/quiz-submissions': typeof AdminQuizSubmissionsIndexRoute
  '/grades/$grade': typeof GradesGradeIndexRoute
  '/admin/lessons/edit/$lessonId': typeof AdminLessonsEditLessonIdRoute
  '/grades/$grade/units/$unit': typeof GradesGradeUnitsUnitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/resource-library': typeof ResourceLibraryRoute
  '/resources': typeof ResourcesRoute
  '/student': typeof StudentRouteWithChildren
  '/student-dashboard': typeof StudentDashboardRoute
  '/video-lessons': typeof VideoLessonsRoute
  '/admin/upload-test': typeof AdminUploadTestRoute
  '/announcements/$slug': typeof AnnouncementsSlugRoute
  '/categories/$category': typeof CategoriesCategoryRoute
  '/parent/$slug': typeof ParentSlugRoute
  '/parent/dashboard': typeof ParentDashboardRoute
  '/parent/settings': typeof ParentSettingsRoute
  '/quizzes/$slug': typeof QuizzesSlugRoute
  '/student/profile': typeof StudentProfileRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/announcements/': typeof AnnouncementsIndexRoute
  '/grades/': typeof GradesIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/quizzes/': typeof QuizzesIndexRoute
  '/student/': typeof StudentIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/grades/$grade/$lesson': typeof GradesGradeLessonRoute
  '/admin/analytics/': typeof AdminAnalyticsIndexRoute
  '/admin/lessons/': typeof AdminLessonsIndexRoute
  '/admin/quiz-submissions/': typeof AdminQuizSubmissionsIndexRoute
  '/grades/$grade/': typeof GradesGradeIndexRoute
  '/admin/lessons/edit/$lessonId': typeof AdminLessonsEditLessonIdRoute
  '/grades/$grade/units/$unit': typeof GradesGradeUnitsUnitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/admin-login'
    | '/auth'
    | '/contact'
    | '/hall-of-fame'
    | '/resource-library'
    | '/resources'
    | '/student'
    | '/student-dashboard'
    | '/video-lessons'
    | '/admin/upload-test'
    | '/announcements/$slug'
    | '/categories/$category'
    | '/parent/$slug'
    | '/parent/dashboard'
    | '/parent/settings'
    | '/quizzes/$slug'
    | '/student/profile'
    | '/videos/$slug'
    | '/admin/'
    | '/announcements/'
    | '/grades/'
    | '/parent/'
    | '/quizzes/'
    | '/student/'
    | '/videos/'
    | '/grades/$grade/$lesson'
    | '/admin/analytics/'
    | '/admin/lessons/'
    | '/admin/quiz-submissions/'
    | '/grades/$grade/'
    | '/admin/lessons/edit/$lessonId'
    | '/grades/$grade/units/$unit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin-login'
    | '/auth'
    | '/contact'
    | '/hall-of-fame'
    | '/resource-library'
    | '/resources'
    | '/student-dashboard'
    | '/video-lessons'
    | '/admin/upload-test'
    | '/announcements/$slug'
    | '/categories/$category'
    | '/parent/$slug'
    | '/parent/dashboard'
    | '/parent/settings'
    | '/quizzes/$slug'
    | '/student/profile'
    | '/videos/$slug'
    | '/admin'
    | '/announcements'
    | '/grades'
    | '/parent'
    | '/quizzes'
    | '/student'
    | '/videos'
    | '/grades/$grade/$lesson'
    | '/admin/analytics'
    | '/admin/lessons'
    | '/admin/quiz-submissions'
    | '/grades/$grade'
    | '/admin/lessons/edit/$lessonId'
    | '/grades/$grade/units/$unit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/admin-login'
    | '/auth'
    | '/contact'
    | '/hall-of-fame'
    | '/resource-library'
    | '/resources'
    | '/student'
    | '/student-dashboard'
    | '/video-lessons'
    | '/admin/upload-test'
    | '/announcements/$slug'
    | '/categories/$category'
    | '/parent/$slug'
    | '/parent/dashboard'
    | '/parent/settings'
    | '/quizzes/$slug'
    | '/student/profile'
    | '/videos/$slug'
    | '/admin/'
    | '/announcements/'
    | '/grades/'
    | '/parent/'
    | '/quizzes/'
    | '/student/'
    | '/videos/'
    | '/grades/$grade/$lesson'
    | '/admin/analytics/'
    | '/admin/lessons/'
    | '/admin/quiz-submissions/'
    | '/grades/$grade/'
    | '/admin/lessons/edit/$lessonId'
    | '/grades/$grade/units/$unit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  HallOfFameRoute: typeof HallOfFameRoute
  ResourceLibraryRoute: typeof ResourceLibraryRoute
  ResourcesRoute: typeof ResourcesRoute
  StudentRoute: typeof StudentRouteWithChildren
  StudentDashboardRoute: typeof StudentDashboardRoute
  VideoLessonsRoute: typeof VideoLessonsRoute
  AnnouncementsSlugRoute: typeof AnnouncementsSlugRoute
  CategoriesCategoryRoute: typeof CategoriesCategoryRoute
  ParentSlugRoute: typeof ParentSlugRoute
  ParentDashboardRoute: typeof ParentDashboardRoute
  ParentSettingsRoute: typeof ParentSettingsRoute
  QuizzesSlugRoute: typeof QuizzesSlugRoute
  VideosSlugRoute: typeof VideosSlugRoute
  AnnouncementsIndexRoute: typeof AnnouncementsIndexRoute
  GradesIndexRoute: typeof GradesIndexRoute
  ParentIndexRoute: typeof ParentIndexRoute
  QuizzesIndexRoute: typeof QuizzesIndexRoute
  VideosIndexRoute: typeof VideosIndexRoute
  GradesGradeLessonRoute: typeof GradesGradeLessonRoute
  GradesGradeIndexRoute: typeof GradesGradeIndexRoute
  GradesGradeUnitsUnitRoute: typeof GradesGradeUnitsUnitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video-lessons': {
      id: '/video-lessons'
      path: '/video-lessons'
      fullPath: '/video-lessons'
      preLoaderRoute: typeof VideoLessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-dashboard': {
      id: '/student-dashboard'
      path: '/student-dashboard'
      fullPath: '/student-dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resource-library': {
      id: '/resource-library'
      path: '/resource-library'
      fullPath: '/resource-library'
      preLoaderRoute: typeof ResourceLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hall-of-fame': {
      id: '/hall-of-fame'
      path: '/hall-of-fame'
      fullPath: '/hall-of-fame'
      preLoaderRoute: typeof HallOfFameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/': {
      id: '/videos/'
      path: '/videos'
      fullPath: '/videos/'
      preLoaderRoute: typeof VideosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/quizzes/': {
      id: '/quizzes/'
      path: '/quizzes'
      fullPath: '/quizzes/'
      preLoaderRoute: typeof QuizzesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/': {
      id: '/parent/'
      path: '/parent'
      fullPath: '/parent/'
      preLoaderRoute: typeof ParentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grades/': {
      id: '/grades/'
      path: '/grades'
      fullPath: '/grades/'
      preLoaderRoute: typeof GradesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements/': {
      id: '/announcements/'
      path: '/announcements'
      fullPath: '/announcements/'
      preLoaderRoute: typeof AnnouncementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/videos/$slug': {
      id: '/videos/$slug'
      path: '/videos/$slug'
      fullPath: '/videos/$slug'
      preLoaderRoute: typeof VideosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/quizzes/$slug': {
      id: '/quizzes/$slug'
      path: '/quizzes/$slug'
      fullPath: '/quizzes/$slug'
      preLoaderRoute: typeof QuizzesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/settings': {
      id: '/parent/settings'
      path: '/parent/settings'
      fullPath: '/parent/settings'
      preLoaderRoute: typeof ParentSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/dashboard': {
      id: '/parent/dashboard'
      path: '/parent/dashboard'
      fullPath: '/parent/dashboard'
      preLoaderRoute: typeof ParentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/$slug': {
      id: '/parent/$slug'
      path: '/parent/$slug'
      fullPath: '/parent/$slug'
      preLoaderRoute: typeof ParentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$category': {
      id: '/categories/$category'
      path: '/categories/$category'
      fullPath: '/categories/$category'
      preLoaderRoute: typeof CategoriesCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements/$slug': {
      id: '/announcements/$slug'
      path: '/announcements/$slug'
      fullPath: '/announcements/$slug'
      preLoaderRoute: typeof AnnouncementsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/upload-test': {
      id: '/admin/upload-test'
      path: '/upload-test'
      fullPath: '/admin/upload-test'
      preLoaderRoute: typeof AdminUploadTestRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/grades/$grade/': {
      id: '/grades/$grade/'
      path: '/grades/$grade'
      fullPath: '/grades/$grade/'
      preLoaderRoute: typeof GradesGradeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/quiz-submissions/': {
      id: '/admin/quiz-submissions/'
      path: '/quiz-submissions'
      fullPath: '/admin/quiz-submissions/'
      preLoaderRoute: typeof AdminQuizSubmissionsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/lessons/': {
      id: '/admin/lessons/'
      path: '/lessons'
      fullPath: '/admin/lessons/'
      preLoaderRoute: typeof AdminLessonsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics/': {
      id: '/admin/analytics/'
      path: '/analytics'
      fullPath: '/admin/analytics/'
      preLoaderRoute: typeof AdminAnalyticsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/grades/$grade/$lesson': {
      id: '/grades/$grade/$lesson'
      path: '/grades/$grade/$lesson'
      fullPath: '/grades/$grade/$lesson'
      preLoaderRoute: typeof GradesGradeLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grades/$grade/units/$unit': {
      id: '/grades/$grade/units/$unit'
      path: '/grades/$grade/units/$unit'
      fullPath: '/grades/$grade/units/$unit'
      preLoaderRoute: typeof GradesGradeUnitsUnitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/lessons/edit/$lessonId': {
      id: '/admin/lessons/edit/$lessonId'
      path: '/lessons/edit/$lessonId'
      fullPath: '/admin/lessons/edit/$lessonId'
      preLoaderRoute: typeof AdminLessonsEditLessonIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminUploadTestRoute: typeof AdminUploadTestRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAnalyticsIndexRoute: typeof AdminAnalyticsIndexRoute
  AdminLessonsIndexRoute: typeof AdminLessonsIndexRoute
  AdminQuizSubmissionsIndexRoute: typeof AdminQuizSubmissionsIndexRoute
  AdminLessonsEditLessonIdRoute: typeof AdminLessonsEditLessonIdRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminUploadTestRoute: AdminUploadTestRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAnalyticsIndexRoute: AdminAnalyticsIndexRoute,
  AdminLessonsIndexRoute: AdminLessonsIndexRoute,
  AdminQuizSubmissionsIndexRoute: AdminQuizSubmissionsIndexRoute,
  AdminLessonsEditLessonIdRoute: AdminLessonsEditLessonIdRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface StudentRouteChildren {
  StudentProfileRoute: typeof StudentProfileRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentProfileRoute: StudentProfileRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminLoginRoute: AdminLoginRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  HallOfFameRoute: HallOfFameRoute,
  ResourceLibraryRoute: ResourceLibraryRoute,
  ResourcesRoute: ResourcesRoute,
  StudentRoute: StudentRouteWithChildren,
  StudentDashboardRoute: StudentDashboardRoute,
  VideoLessonsRoute: VideoLessonsRoute,
  AnnouncementsSlugRoute: AnnouncementsSlugRoute,
  CategoriesCategoryRoute: CategoriesCategoryRoute,
  ParentSlugRoute: ParentSlugRoute,
  ParentDashboardRoute: ParentDashboardRoute,
  ParentSettingsRoute: ParentSettingsRoute,
  QuizzesSlugRoute: QuizzesSlugRoute,
  VideosSlugRoute: VideosSlugRoute,
  AnnouncementsIndexRoute: AnnouncementsIndexRoute,
  GradesIndexRoute: GradesIndexRoute,
  ParentIndexRoute: ParentIndexRoute,
  QuizzesIndexRoute: QuizzesIndexRoute,
  VideosIndexRoute: VideosIndexRoute,
  GradesGradeLessonRoute: GradesGradeLessonRoute,
  GradesGradeIndexRoute: GradesGradeIndexRoute,
  GradesGradeUnitsUnitRoute: GradesGradeUnitsUnitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
