/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoLessonsRouteImport } from './routes/video-lessons'
import { Route as StudentDashboardRouteImport } from './routes/student-dashboard'
import { Route as StudentRouteImport } from './routes/student'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ResourceLibraryRouteImport } from './routes/resource-library'
import { Route as HallOfFameRouteImport } from './routes/hall-of-fame'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as TeacherRouteRouteImport } from './routes/teacher/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideosIndexRouteImport } from './routes/videos.index'
import { Route as TeacherIndexRouteImport } from './routes/teacher/index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as QuizzesIndexRouteImport } from './routes/quizzes.index'
import { Route as ParentIndexRouteImport } from './routes/parent.index'
import { Route as GradesIndexRouteImport } from './routes/grades.index'
import { Route as AssignmentsIndexRouteImport } from './routes/assignments.index'
import { Route as AnnouncementsIndexRouteImport } from './routes/announcements.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as VideosSlugRouteImport } from './routes/videos.$slug'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as QuizzesSlugRouteImport } from './routes/quizzes.$slug'
import { Route as ParentSettingsRouteImport } from './routes/parent.settings'
import { Route as ParentDashboardRouteImport } from './routes/parent.dashboard'
import { Route as ParentSlugRouteImport } from './routes/parent.$slug'
import { Route as CategoriesCategoryRouteImport } from './routes/categories.$category'
import { Route as AssignmentsAssignmentIdRouteImport } from './routes/assignments.$assignmentId'
import { Route as AnnouncementsSlugRouteImport } from './routes/announcements.$slug'
import { Route as AdminUploadTestRouteImport } from './routes/admin/upload-test'
import { Route as TeacherWeeklyPlanningIndexRouteImport } from './routes/teacher/weekly-planning.index'
import { Route as TeacherVideosIndexRouteImport } from './routes/teacher/videos.index'
import { Route as TeacherUsersIndexRouteImport } from './routes/teacher/users.index'
import { Route as TeacherUnitsIndexRouteImport } from './routes/teacher/units.index'
import { Route as TeacherStudentsIndexRouteImport } from './routes/teacher/students.index'
import { Route as TeacherResourcesIndexRouteImport } from './routes/teacher/resources.index'
import { Route as TeacherQuizzesIndexRouteImport } from './routes/teacher/quizzes.index'
import { Route as TeacherPerformanceIndexRouteImport } from './routes/teacher/performance.index'
import { Route as TeacherLessonsIndexRouteImport } from './routes/teacher/lessons.index'
import { Route as TeacherCurriculumIndexRouteImport } from './routes/teacher/curriculum.index'
import { Route as TeacherClassesIndexRouteImport } from './routes/teacher/classes.index'
import { Route as TeacherAssignmentsIndexRouteImport } from './routes/teacher/assignments.index'
import { Route as TeacherArticlesIndexRouteImport } from './routes/teacher/articles.index'
import { Route as TeacherAnnouncementsIndexRouteImport } from './routes/teacher/announcements.index'
import { Route as GradesGradeIndexRouteImport } from './routes/grades.$grade.index'
import { Route as AdminTeachersIndexRouteImport } from './routes/admin/teachers.index'
import { Route as AdminQuizSubmissionsIndexRouteImport } from './routes/admin/quiz-submissions.index'
import { Route as AdminLessonsIndexRouteImport } from './routes/admin/lessons.index'
import { Route as AdminAssignmentsIndexRouteImport } from './routes/admin/assignments.index'
import { Route as AdminAnalyticsIndexRouteImport } from './routes/admin/analytics.index'
import { Route as TeacherWeeklyPlanningNewRouteImport } from './routes/teacher/weekly-planning.new'
import { Route as TeacherWeeklyPlanningPlanIdRouteImport } from './routes/teacher/weekly-planning.$planId'
import { Route as TeacherVideosNewRouteImport } from './routes/teacher/videos.new'
import { Route as TeacherStudentsStudentIdRouteImport } from './routes/teacher/students.$studentId'
import { Route as TeacherResourcesNewRouteImport } from './routes/teacher/resources.new'
import { Route as TeacherLessonsNewRouteImport } from './routes/teacher/lessons.new'
import { Route as TeacherArticlesNewRouteImport } from './routes/teacher/articles.new'
import { Route as TeacherAnnouncementsNewRouteImport } from './routes/teacher/announcements.new'
import { Route as GradesGradeLessonRouteImport } from './routes/grades.$grade.$lesson'
import { Route as TeacherWeeklyPlanningPlanIdIndexRouteImport } from './routes/teacher/weekly-planning.$planId.index'
import { Route as TeacherQuizzesManageIndexRouteImport } from './routes/teacher/quizzes.manage.index'
import { Route as TeacherAssignmentsSubmissionsIndexRouteImport } from './routes/teacher/assignments.submissions.index'
import { Route as TeacherWeeklyPlanningPlanIdPrintRouteImport } from './routes/teacher/weekly-planning.$planId.print'
import { Route as TeacherWeeklyPlanningPlanIdEditRouteImport } from './routes/teacher/weekly-planning.$planId.edit'
import { Route as TeacherLessonsEditLessonIdRouteImport } from './routes/teacher.lessons.edit.$lessonId'
import { Route as GradesGradeUnitsUnitRouteImport } from './routes/grades.$grade.units.$unit'
import { Route as AdminLessonsEditLessonIdRouteImport } from './routes/admin.lessons.edit.$lessonId'

const VideoLessonsRoute = VideoLessonsRouteImport.update({
  id: '/video-lessons',
  path: '/video-lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student-dashboard',
  path: '/student-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourceLibraryRoute = ResourceLibraryRouteImport.update({
  id: '/resource-library',
  path: '/resource-library',
  getParentRoute: () => rootRouteImport,
} as any)
const HallOfFameRoute = HallOfFameRouteImport.update({
  id: '/hall-of-fame',
  path: '/hall-of-fame',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRouteRoute = TeacherRouteRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIndexRoute = VideosIndexRouteImport.update({
  id: '/videos/',
  path: '/videos/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const QuizzesIndexRoute = QuizzesIndexRouteImport.update({
  id: '/quizzes/',
  path: '/quizzes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentIndexRoute = ParentIndexRouteImport.update({
  id: '/parent/',
  path: '/parent/',
  getParentRoute: () => rootRouteImport,
} as any)
const GradesIndexRoute = GradesIndexRouteImport.update({
  id: '/grades/',
  path: '/grades/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsIndexRoute = AssignmentsIndexRouteImport.update({
  id: '/assignments/',
  path: '/assignments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsIndexRoute = AnnouncementsIndexRouteImport.update({
  id: '/announcements/',
  path: '/announcements/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const VideosSlugRoute = VideosSlugRouteImport.update({
  id: '/videos/$slug',
  path: '/videos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const QuizzesSlugRoute = QuizzesSlugRouteImport.update({
  id: '/quizzes/$slug',
  path: '/quizzes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentSettingsRoute = ParentSettingsRouteImport.update({
  id: '/parent/settings',
  path: '/parent/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentDashboardRoute = ParentDashboardRouteImport.update({
  id: '/parent/dashboard',
  path: '/parent/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentSlugRoute = ParentSlugRouteImport.update({
  id: '/parent/$slug',
  path: '/parent/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCategoryRoute = CategoriesCategoryRouteImport.update({
  id: '/categories/$category',
  path: '/categories/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsAssignmentIdRoute = AssignmentsAssignmentIdRouteImport.update({
  id: '/assignments/$assignmentId',
  path: '/assignments/$assignmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsSlugRoute = AnnouncementsSlugRouteImport.update({
  id: '/announcements/$slug',
  path: '/announcements/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUploadTestRoute = AdminUploadTestRouteImport.update({
  id: '/upload-test',
  path: '/upload-test',
  getParentRoute: () => AdminRouteRoute,
} as any)
const TeacherWeeklyPlanningIndexRoute =
  TeacherWeeklyPlanningIndexRouteImport.update({
    id: '/weekly-planning/',
    path: '/weekly-planning/',
    getParentRoute: () => TeacherRouteRoute,
  } as any)
const TeacherVideosIndexRoute = TeacherVideosIndexRouteImport.update({
  id: '/videos/',
  path: '/videos/',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherUsersIndexRoute = TeacherUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherUnitsIndexRoute = TeacherUnitsIndexRouteImport.update({
  id: '/units/',
  path: '/units/',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherStudentsIndexRoute = TeacherStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherResourcesIndexRoute = TeacherResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherQuizzesIndexRoute = TeacherQuizzesIndexRouteImport.update({
  id: '/quizzes/',
  path: '/quizzes/',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherPerformanceIndexRoute = TeacherPerformanceIndexRouteImport.update({
  id: '/performance/',
  path: '/performance/',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherLessonsIndexRoute = TeacherLessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherCurriculumIndexRoute = TeacherCurriculumIndexRouteImport.update({
  id: '/curriculum/',
  path: '/curriculum/',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherClassesIndexRoute = TeacherClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherAssignmentsIndexRoute = TeacherAssignmentsIndexRouteImport.update({
  id: '/assignments/',
  path: '/assignments/',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherArticlesIndexRoute = TeacherArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherAnnouncementsIndexRoute =
  TeacherAnnouncementsIndexRouteImport.update({
    id: '/announcements/',
    path: '/announcements/',
    getParentRoute: () => TeacherRouteRoute,
  } as any)
const GradesGradeIndexRoute = GradesGradeIndexRouteImport.update({
  id: '/grades/$grade/',
  path: '/grades/$grade/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeachersIndexRoute = AdminTeachersIndexRouteImport.update({
  id: '/teachers/',
  path: '/teachers/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminQuizSubmissionsIndexRoute =
  AdminQuizSubmissionsIndexRouteImport.update({
    id: '/quiz-submissions/',
    path: '/quiz-submissions/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminLessonsIndexRoute = AdminLessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAssignmentsIndexRoute = AdminAssignmentsIndexRouteImport.update({
  id: '/assignments/',
  path: '/assignments/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsIndexRoute = AdminAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const TeacherWeeklyPlanningNewRoute =
  TeacherWeeklyPlanningNewRouteImport.update({
    id: '/weekly-planning/new',
    path: '/weekly-planning/new',
    getParentRoute: () => TeacherRouteRoute,
  } as any)
const TeacherWeeklyPlanningPlanIdRoute =
  TeacherWeeklyPlanningPlanIdRouteImport.update({
    id: '/weekly-planning/$planId',
    path: '/weekly-planning/$planId',
    getParentRoute: () => TeacherRouteRoute,
  } as any)
const TeacherVideosNewRoute = TeacherVideosNewRouteImport.update({
  id: '/videos/new',
  path: '/videos/new',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherStudentsStudentIdRoute =
  TeacherStudentsStudentIdRouteImport.update({
    id: '/students/$studentId',
    path: '/students/$studentId',
    getParentRoute: () => TeacherRouteRoute,
  } as any)
const TeacherResourcesNewRoute = TeacherResourcesNewRouteImport.update({
  id: '/resources/new',
  path: '/resources/new',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherLessonsNewRoute = TeacherLessonsNewRouteImport.update({
  id: '/lessons/new',
  path: '/lessons/new',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherArticlesNewRoute = TeacherArticlesNewRouteImport.update({
  id: '/articles/new',
  path: '/articles/new',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherAnnouncementsNewRoute = TeacherAnnouncementsNewRouteImport.update({
  id: '/announcements/new',
  path: '/announcements/new',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const GradesGradeLessonRoute = GradesGradeLessonRouteImport.update({
  id: '/grades/$grade/$lesson',
  path: '/grades/$grade/$lesson',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherWeeklyPlanningPlanIdIndexRoute =
  TeacherWeeklyPlanningPlanIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TeacherWeeklyPlanningPlanIdRoute,
  } as any)
const TeacherQuizzesManageIndexRoute =
  TeacherQuizzesManageIndexRouteImport.update({
    id: '/quizzes/manage/',
    path: '/quizzes/manage/',
    getParentRoute: () => TeacherRouteRoute,
  } as any)
const TeacherAssignmentsSubmissionsIndexRoute =
  TeacherAssignmentsSubmissionsIndexRouteImport.update({
    id: '/assignments/submissions/',
    path: '/assignments/submissions/',
    getParentRoute: () => TeacherRouteRoute,
  } as any)
const TeacherWeeklyPlanningPlanIdPrintRoute =
  TeacherWeeklyPlanningPlanIdPrintRouteImport.update({
    id: '/print',
    path: '/print',
    getParentRoute: () => TeacherWeeklyPlanningPlanIdRoute,
  } as any)
const TeacherWeeklyPlanningPlanIdEditRoute =
  TeacherWeeklyPlanningPlanIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => TeacherWeeklyPlanningPlanIdRoute,
  } as any)
const TeacherLessonsEditLessonIdRoute =
  TeacherLessonsEditLessonIdRouteImport.update({
    id: '/lessons/edit/$lessonId',
    path: '/lessons/edit/$lessonId',
    getParentRoute: () => TeacherRouteRoute,
  } as any)
const GradesGradeUnitsUnitRoute = GradesGradeUnitsUnitRouteImport.update({
  id: '/grades/$grade/units/$unit',
  path: '/grades/$grade/units/$unit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLessonsEditLessonIdRoute =
  AdminLessonsEditLessonIdRouteImport.update({
    id: '/lessons/edit/$lessonId',
    path: '/lessons/edit/$lessonId',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/teacher': typeof TeacherRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/resource-library': typeof ResourceLibraryRoute
  '/resources': typeof ResourcesRoute
  '/student': typeof StudentRouteWithChildren
  '/student-dashboard': typeof StudentDashboardRoute
  '/video-lessons': typeof VideoLessonsRoute
  '/admin/upload-test': typeof AdminUploadTestRoute
  '/announcements/$slug': typeof AnnouncementsSlugRoute
  '/assignments/$assignmentId': typeof AssignmentsAssignmentIdRoute
  '/categories/$category': typeof CategoriesCategoryRoute
  '/parent/$slug': typeof ParentSlugRoute
  '/parent/dashboard': typeof ParentDashboardRoute
  '/parent/settings': typeof ParentSettingsRoute
  '/quizzes/$slug': typeof QuizzesSlugRoute
  '/student/profile': typeof StudentProfileRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/announcements/': typeof AnnouncementsIndexRoute
  '/assignments/': typeof AssignmentsIndexRoute
  '/grades/': typeof GradesIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/quizzes/': typeof QuizzesIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/grades/$grade/$lesson': typeof GradesGradeLessonRoute
  '/teacher/announcements/new': typeof TeacherAnnouncementsNewRoute
  '/teacher/articles/new': typeof TeacherArticlesNewRoute
  '/teacher/lessons/new': typeof TeacherLessonsNewRoute
  '/teacher/resources/new': typeof TeacherResourcesNewRoute
  '/teacher/students/$studentId': typeof TeacherStudentsStudentIdRoute
  '/teacher/videos/new': typeof TeacherVideosNewRoute
  '/teacher/weekly-planning/$planId': typeof TeacherWeeklyPlanningPlanIdRouteWithChildren
  '/teacher/weekly-planning/new': typeof TeacherWeeklyPlanningNewRoute
  '/admin/analytics/': typeof AdminAnalyticsIndexRoute
  '/admin/assignments/': typeof AdminAssignmentsIndexRoute
  '/admin/lessons/': typeof AdminLessonsIndexRoute
  '/admin/quiz-submissions/': typeof AdminQuizSubmissionsIndexRoute
  '/admin/teachers/': typeof AdminTeachersIndexRoute
  '/grades/$grade/': typeof GradesGradeIndexRoute
  '/teacher/announcements/': typeof TeacherAnnouncementsIndexRoute
  '/teacher/articles/': typeof TeacherArticlesIndexRoute
  '/teacher/assignments/': typeof TeacherAssignmentsIndexRoute
  '/teacher/classes/': typeof TeacherClassesIndexRoute
  '/teacher/curriculum/': typeof TeacherCurriculumIndexRoute
  '/teacher/lessons/': typeof TeacherLessonsIndexRoute
  '/teacher/performance/': typeof TeacherPerformanceIndexRoute
  '/teacher/quizzes/': typeof TeacherQuizzesIndexRoute
  '/teacher/resources/': typeof TeacherResourcesIndexRoute
  '/teacher/students/': typeof TeacherStudentsIndexRoute
  '/teacher/units/': typeof TeacherUnitsIndexRoute
  '/teacher/users/': typeof TeacherUsersIndexRoute
  '/teacher/videos/': typeof TeacherVideosIndexRoute
  '/teacher/weekly-planning/': typeof TeacherWeeklyPlanningIndexRoute
  '/admin/lessons/edit/$lessonId': typeof AdminLessonsEditLessonIdRoute
  '/grades/$grade/units/$unit': typeof GradesGradeUnitsUnitRoute
  '/teacher/lessons/edit/$lessonId': typeof TeacherLessonsEditLessonIdRoute
  '/teacher/weekly-planning/$planId/edit': typeof TeacherWeeklyPlanningPlanIdEditRoute
  '/teacher/weekly-planning/$planId/print': typeof TeacherWeeklyPlanningPlanIdPrintRoute
  '/teacher/assignments/submissions/': typeof TeacherAssignmentsSubmissionsIndexRoute
  '/teacher/quizzes/manage/': typeof TeacherQuizzesManageIndexRoute
  '/teacher/weekly-planning/$planId/': typeof TeacherWeeklyPlanningPlanIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/resource-library': typeof ResourceLibraryRoute
  '/resources': typeof ResourcesRoute
  '/student-dashboard': typeof StudentDashboardRoute
  '/video-lessons': typeof VideoLessonsRoute
  '/admin/upload-test': typeof AdminUploadTestRoute
  '/announcements/$slug': typeof AnnouncementsSlugRoute
  '/assignments/$assignmentId': typeof AssignmentsAssignmentIdRoute
  '/categories/$category': typeof CategoriesCategoryRoute
  '/parent/$slug': typeof ParentSlugRoute
  '/parent/dashboard': typeof ParentDashboardRoute
  '/parent/settings': typeof ParentSettingsRoute
  '/quizzes/$slug': typeof QuizzesSlugRoute
  '/student/profile': typeof StudentProfileRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/admin': typeof AdminIndexRoute
  '/announcements': typeof AnnouncementsIndexRoute
  '/assignments': typeof AssignmentsIndexRoute
  '/grades': typeof GradesIndexRoute
  '/parent': typeof ParentIndexRoute
  '/quizzes': typeof QuizzesIndexRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/videos': typeof VideosIndexRoute
  '/grades/$grade/$lesson': typeof GradesGradeLessonRoute
  '/teacher/announcements/new': typeof TeacherAnnouncementsNewRoute
  '/teacher/articles/new': typeof TeacherArticlesNewRoute
  '/teacher/lessons/new': typeof TeacherLessonsNewRoute
  '/teacher/resources/new': typeof TeacherResourcesNewRoute
  '/teacher/students/$studentId': typeof TeacherStudentsStudentIdRoute
  '/teacher/videos/new': typeof TeacherVideosNewRoute
  '/teacher/weekly-planning/new': typeof TeacherWeeklyPlanningNewRoute
  '/admin/analytics': typeof AdminAnalyticsIndexRoute
  '/admin/assignments': typeof AdminAssignmentsIndexRoute
  '/admin/lessons': typeof AdminLessonsIndexRoute
  '/admin/quiz-submissions': typeof AdminQuizSubmissionsIndexRoute
  '/admin/teachers': typeof AdminTeachersIndexRoute
  '/grades/$grade': typeof GradesGradeIndexRoute
  '/teacher/announcements': typeof TeacherAnnouncementsIndexRoute
  '/teacher/articles': typeof TeacherArticlesIndexRoute
  '/teacher/assignments': typeof TeacherAssignmentsIndexRoute
  '/teacher/classes': typeof TeacherClassesIndexRoute
  '/teacher/curriculum': typeof TeacherCurriculumIndexRoute
  '/teacher/lessons': typeof TeacherLessonsIndexRoute
  '/teacher/performance': typeof TeacherPerformanceIndexRoute
  '/teacher/quizzes': typeof TeacherQuizzesIndexRoute
  '/teacher/resources': typeof TeacherResourcesIndexRoute
  '/teacher/students': typeof TeacherStudentsIndexRoute
  '/teacher/units': typeof TeacherUnitsIndexRoute
  '/teacher/users': typeof TeacherUsersIndexRoute
  '/teacher/videos': typeof TeacherVideosIndexRoute
  '/teacher/weekly-planning': typeof TeacherWeeklyPlanningIndexRoute
  '/admin/lessons/edit/$lessonId': typeof AdminLessonsEditLessonIdRoute
  '/grades/$grade/units/$unit': typeof GradesGradeUnitsUnitRoute
  '/teacher/lessons/edit/$lessonId': typeof TeacherLessonsEditLessonIdRoute
  '/teacher/weekly-planning/$planId/edit': typeof TeacherWeeklyPlanningPlanIdEditRoute
  '/teacher/weekly-planning/$planId/print': typeof TeacherWeeklyPlanningPlanIdPrintRoute
  '/teacher/assignments/submissions': typeof TeacherAssignmentsSubmissionsIndexRoute
  '/teacher/quizzes/manage': typeof TeacherQuizzesManageIndexRoute
  '/teacher/weekly-planning/$planId': typeof TeacherWeeklyPlanningPlanIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/teacher': typeof TeacherRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/resource-library': typeof ResourceLibraryRoute
  '/resources': typeof ResourcesRoute
  '/student': typeof StudentRouteWithChildren
  '/student-dashboard': typeof StudentDashboardRoute
  '/video-lessons': typeof VideoLessonsRoute
  '/admin/upload-test': typeof AdminUploadTestRoute
  '/announcements/$slug': typeof AnnouncementsSlugRoute
  '/assignments/$assignmentId': typeof AssignmentsAssignmentIdRoute
  '/categories/$category': typeof CategoriesCategoryRoute
  '/parent/$slug': typeof ParentSlugRoute
  '/parent/dashboard': typeof ParentDashboardRoute
  '/parent/settings': typeof ParentSettingsRoute
  '/quizzes/$slug': typeof QuizzesSlugRoute
  '/student/profile': typeof StudentProfileRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/announcements/': typeof AnnouncementsIndexRoute
  '/assignments/': typeof AssignmentsIndexRoute
  '/grades/': typeof GradesIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/quizzes/': typeof QuizzesIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/grades/$grade/$lesson': typeof GradesGradeLessonRoute
  '/teacher/announcements/new': typeof TeacherAnnouncementsNewRoute
  '/teacher/articles/new': typeof TeacherArticlesNewRoute
  '/teacher/lessons/new': typeof TeacherLessonsNewRoute
  '/teacher/resources/new': typeof TeacherResourcesNewRoute
  '/teacher/students/$studentId': typeof TeacherStudentsStudentIdRoute
  '/teacher/videos/new': typeof TeacherVideosNewRoute
  '/teacher/weekly-planning/$planId': typeof TeacherWeeklyPlanningPlanIdRouteWithChildren
  '/teacher/weekly-planning/new': typeof TeacherWeeklyPlanningNewRoute
  '/admin/analytics/': typeof AdminAnalyticsIndexRoute
  '/admin/assignments/': typeof AdminAssignmentsIndexRoute
  '/admin/lessons/': typeof AdminLessonsIndexRoute
  '/admin/quiz-submissions/': typeof AdminQuizSubmissionsIndexRoute
  '/admin/teachers/': typeof AdminTeachersIndexRoute
  '/grades/$grade/': typeof GradesGradeIndexRoute
  '/teacher/announcements/': typeof TeacherAnnouncementsIndexRoute
  '/teacher/articles/': typeof TeacherArticlesIndexRoute
  '/teacher/assignments/': typeof TeacherAssignmentsIndexRoute
  '/teacher/classes/': typeof TeacherClassesIndexRoute
  '/teacher/curriculum/': typeof TeacherCurriculumIndexRoute
  '/teacher/lessons/': typeof TeacherLessonsIndexRoute
  '/teacher/performance/': typeof TeacherPerformanceIndexRoute
  '/teacher/quizzes/': typeof TeacherQuizzesIndexRoute
  '/teacher/resources/': typeof TeacherResourcesIndexRoute
  '/teacher/students/': typeof TeacherStudentsIndexRoute
  '/teacher/units/': typeof TeacherUnitsIndexRoute
  '/teacher/users/': typeof TeacherUsersIndexRoute
  '/teacher/videos/': typeof TeacherVideosIndexRoute
  '/teacher/weekly-planning/': typeof TeacherWeeklyPlanningIndexRoute
  '/admin/lessons/edit/$lessonId': typeof AdminLessonsEditLessonIdRoute
  '/grades/$grade/units/$unit': typeof GradesGradeUnitsUnitRoute
  '/teacher/lessons/edit/$lessonId': typeof TeacherLessonsEditLessonIdRoute
  '/teacher/weekly-planning/$planId/edit': typeof TeacherWeeklyPlanningPlanIdEditRoute
  '/teacher/weekly-planning/$planId/print': typeof TeacherWeeklyPlanningPlanIdPrintRoute
  '/teacher/assignments/submissions/': typeof TeacherAssignmentsSubmissionsIndexRoute
  '/teacher/quizzes/manage/': typeof TeacherQuizzesManageIndexRoute
  '/teacher/weekly-planning/$planId/': typeof TeacherWeeklyPlanningPlanIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/teacher'
    | '/about'
    | '/admin-login'
    | '/auth'
    | '/contact'
    | '/hall-of-fame'
    | '/resource-library'
    | '/resources'
    | '/student'
    | '/student-dashboard'
    | '/video-lessons'
    | '/admin/upload-test'
    | '/announcements/$slug'
    | '/assignments/$assignmentId'
    | '/categories/$category'
    | '/parent/$slug'
    | '/parent/dashboard'
    | '/parent/settings'
    | '/quizzes/$slug'
    | '/student/profile'
    | '/videos/$slug'
    | '/admin/'
    | '/announcements/'
    | '/assignments/'
    | '/grades/'
    | '/parent/'
    | '/quizzes/'
    | '/student/'
    | '/teacher/'
    | '/videos/'
    | '/grades/$grade/$lesson'
    | '/teacher/announcements/new'
    | '/teacher/articles/new'
    | '/teacher/lessons/new'
    | '/teacher/resources/new'
    | '/teacher/students/$studentId'
    | '/teacher/videos/new'
    | '/teacher/weekly-planning/$planId'
    | '/teacher/weekly-planning/new'
    | '/admin/analytics/'
    | '/admin/assignments/'
    | '/admin/lessons/'
    | '/admin/quiz-submissions/'
    | '/admin/teachers/'
    | '/grades/$grade/'
    | '/teacher/announcements/'
    | '/teacher/articles/'
    | '/teacher/assignments/'
    | '/teacher/classes/'
    | '/teacher/curriculum/'
    | '/teacher/lessons/'
    | '/teacher/performance/'
    | '/teacher/quizzes/'
    | '/teacher/resources/'
    | '/teacher/students/'
    | '/teacher/units/'
    | '/teacher/users/'
    | '/teacher/videos/'
    | '/teacher/weekly-planning/'
    | '/admin/lessons/edit/$lessonId'
    | '/grades/$grade/units/$unit'
    | '/teacher/lessons/edit/$lessonId'
    | '/teacher/weekly-planning/$planId/edit'
    | '/teacher/weekly-planning/$planId/print'
    | '/teacher/assignments/submissions/'
    | '/teacher/quizzes/manage/'
    | '/teacher/weekly-planning/$planId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin-login'
    | '/auth'
    | '/contact'
    | '/hall-of-fame'
    | '/resource-library'
    | '/resources'
    | '/student-dashboard'
    | '/video-lessons'
    | '/admin/upload-test'
    | '/announcements/$slug'
    | '/assignments/$assignmentId'
    | '/categories/$category'
    | '/parent/$slug'
    | '/parent/dashboard'
    | '/parent/settings'
    | '/quizzes/$slug'
    | '/student/profile'
    | '/videos/$slug'
    | '/admin'
    | '/announcements'
    | '/assignments'
    | '/grades'
    | '/parent'
    | '/quizzes'
    | '/student'
    | '/teacher'
    | '/videos'
    | '/grades/$grade/$lesson'
    | '/teacher/announcements/new'
    | '/teacher/articles/new'
    | '/teacher/lessons/new'
    | '/teacher/resources/new'
    | '/teacher/students/$studentId'
    | '/teacher/videos/new'
    | '/teacher/weekly-planning/new'
    | '/admin/analytics'
    | '/admin/assignments'
    | '/admin/lessons'
    | '/admin/quiz-submissions'
    | '/admin/teachers'
    | '/grades/$grade'
    | '/teacher/announcements'
    | '/teacher/articles'
    | '/teacher/assignments'
    | '/teacher/classes'
    | '/teacher/curriculum'
    | '/teacher/lessons'
    | '/teacher/performance'
    | '/teacher/quizzes'
    | '/teacher/resources'
    | '/teacher/students'
    | '/teacher/units'
    | '/teacher/users'
    | '/teacher/videos'
    | '/teacher/weekly-planning'
    | '/admin/lessons/edit/$lessonId'
    | '/grades/$grade/units/$unit'
    | '/teacher/lessons/edit/$lessonId'
    | '/teacher/weekly-planning/$planId/edit'
    | '/teacher/weekly-planning/$planId/print'
    | '/teacher/assignments/submissions'
    | '/teacher/quizzes/manage'
    | '/teacher/weekly-planning/$planId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/teacher'
    | '/about'
    | '/admin-login'
    | '/auth'
    | '/contact'
    | '/hall-of-fame'
    | '/resource-library'
    | '/resources'
    | '/student'
    | '/student-dashboard'
    | '/video-lessons'
    | '/admin/upload-test'
    | '/announcements/$slug'
    | '/assignments/$assignmentId'
    | '/categories/$category'
    | '/parent/$slug'
    | '/parent/dashboard'
    | '/parent/settings'
    | '/quizzes/$slug'
    | '/student/profile'
    | '/videos/$slug'
    | '/admin/'
    | '/announcements/'
    | '/assignments/'
    | '/grades/'
    | '/parent/'
    | '/quizzes/'
    | '/student/'
    | '/teacher/'
    | '/videos/'
    | '/grades/$grade/$lesson'
    | '/teacher/announcements/new'
    | '/teacher/articles/new'
    | '/teacher/lessons/new'
    | '/teacher/resources/new'
    | '/teacher/students/$studentId'
    | '/teacher/videos/new'
    | '/teacher/weekly-planning/$planId'
    | '/teacher/weekly-planning/new'
    | '/admin/analytics/'
    | '/admin/assignments/'
    | '/admin/lessons/'
    | '/admin/quiz-submissions/'
    | '/admin/teachers/'
    | '/grades/$grade/'
    | '/teacher/announcements/'
    | '/teacher/articles/'
    | '/teacher/assignments/'
    | '/teacher/classes/'
    | '/teacher/curriculum/'
    | '/teacher/lessons/'
    | '/teacher/performance/'
    | '/teacher/quizzes/'
    | '/teacher/resources/'
    | '/teacher/students/'
    | '/teacher/units/'
    | '/teacher/users/'
    | '/teacher/videos/'
    | '/teacher/weekly-planning/'
    | '/admin/lessons/edit/$lessonId'
    | '/grades/$grade/units/$unit'
    | '/teacher/lessons/edit/$lessonId'
    | '/teacher/weekly-planning/$planId/edit'
    | '/teacher/weekly-planning/$planId/print'
    | '/teacher/assignments/submissions/'
    | '/teacher/quizzes/manage/'
    | '/teacher/weekly-planning/$planId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  TeacherRouteRoute: typeof TeacherRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  HallOfFameRoute: typeof HallOfFameRoute
  ResourceLibraryRoute: typeof ResourceLibraryRoute
  ResourcesRoute: typeof ResourcesRoute
  StudentRoute: typeof StudentRouteWithChildren
  StudentDashboardRoute: typeof StudentDashboardRoute
  VideoLessonsRoute: typeof VideoLessonsRoute
  AnnouncementsSlugRoute: typeof AnnouncementsSlugRoute
  AssignmentsAssignmentIdRoute: typeof AssignmentsAssignmentIdRoute
  CategoriesCategoryRoute: typeof CategoriesCategoryRoute
  ParentSlugRoute: typeof ParentSlugRoute
  ParentDashboardRoute: typeof ParentDashboardRoute
  ParentSettingsRoute: typeof ParentSettingsRoute
  QuizzesSlugRoute: typeof QuizzesSlugRoute
  VideosSlugRoute: typeof VideosSlugRoute
  AnnouncementsIndexRoute: typeof AnnouncementsIndexRoute
  AssignmentsIndexRoute: typeof AssignmentsIndexRoute
  GradesIndexRoute: typeof GradesIndexRoute
  ParentIndexRoute: typeof ParentIndexRoute
  QuizzesIndexRoute: typeof QuizzesIndexRoute
  VideosIndexRoute: typeof VideosIndexRoute
  GradesGradeLessonRoute: typeof GradesGradeLessonRoute
  GradesGradeIndexRoute: typeof GradesGradeIndexRoute
  GradesGradeUnitsUnitRoute: typeof GradesGradeUnitsUnitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video-lessons': {
      id: '/video-lessons'
      path: '/video-lessons'
      fullPath: '/video-lessons'
      preLoaderRoute: typeof VideoLessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-dashboard': {
      id: '/student-dashboard'
      path: '/student-dashboard'
      fullPath: '/student-dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resource-library': {
      id: '/resource-library'
      path: '/resource-library'
      fullPath: '/resource-library'
      preLoaderRoute: typeof ResourceLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hall-of-fame': {
      id: '/hall-of-fame'
      path: '/hall-of-fame'
      fullPath: '/hall-of-fame'
      preLoaderRoute: typeof HallOfFameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/': {
      id: '/videos/'
      path: '/videos'
      fullPath: '/videos/'
      preLoaderRoute: typeof VideosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/quizzes/': {
      id: '/quizzes/'
      path: '/quizzes'
      fullPath: '/quizzes/'
      preLoaderRoute: typeof QuizzesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/': {
      id: '/parent/'
      path: '/parent'
      fullPath: '/parent/'
      preLoaderRoute: typeof ParentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grades/': {
      id: '/grades/'
      path: '/grades'
      fullPath: '/grades/'
      preLoaderRoute: typeof GradesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments/': {
      id: '/assignments/'
      path: '/assignments'
      fullPath: '/assignments/'
      preLoaderRoute: typeof AssignmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements/': {
      id: '/announcements/'
      path: '/announcements'
      fullPath: '/announcements/'
      preLoaderRoute: typeof AnnouncementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/videos/$slug': {
      id: '/videos/$slug'
      path: '/videos/$slug'
      fullPath: '/videos/$slug'
      preLoaderRoute: typeof VideosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/quizzes/$slug': {
      id: '/quizzes/$slug'
      path: '/quizzes/$slug'
      fullPath: '/quizzes/$slug'
      preLoaderRoute: typeof QuizzesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/settings': {
      id: '/parent/settings'
      path: '/parent/settings'
      fullPath: '/parent/settings'
      preLoaderRoute: typeof ParentSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/dashboard': {
      id: '/parent/dashboard'
      path: '/parent/dashboard'
      fullPath: '/parent/dashboard'
      preLoaderRoute: typeof ParentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/$slug': {
      id: '/parent/$slug'
      path: '/parent/$slug'
      fullPath: '/parent/$slug'
      preLoaderRoute: typeof ParentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$category': {
      id: '/categories/$category'
      path: '/categories/$category'
      fullPath: '/categories/$category'
      preLoaderRoute: typeof CategoriesCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments/$assignmentId': {
      id: '/assignments/$assignmentId'
      path: '/assignments/$assignmentId'
      fullPath: '/assignments/$assignmentId'
      preLoaderRoute: typeof AssignmentsAssignmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements/$slug': {
      id: '/announcements/$slug'
      path: '/announcements/$slug'
      fullPath: '/announcements/$slug'
      preLoaderRoute: typeof AnnouncementsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/upload-test': {
      id: '/admin/upload-test'
      path: '/upload-test'
      fullPath: '/admin/upload-test'
      preLoaderRoute: typeof AdminUploadTestRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/teacher/weekly-planning/': {
      id: '/teacher/weekly-planning/'
      path: '/weekly-planning'
      fullPath: '/teacher/weekly-planning/'
      preLoaderRoute: typeof TeacherWeeklyPlanningIndexRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/videos/': {
      id: '/teacher/videos/'
      path: '/videos'
      fullPath: '/teacher/videos/'
      preLoaderRoute: typeof TeacherVideosIndexRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/users/': {
      id: '/teacher/users/'
      path: '/users'
      fullPath: '/teacher/users/'
      preLoaderRoute: typeof TeacherUsersIndexRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/units/': {
      id: '/teacher/units/'
      path: '/units'
      fullPath: '/teacher/units/'
      preLoaderRoute: typeof TeacherUnitsIndexRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/students/': {
      id: '/teacher/students/'
      path: '/students'
      fullPath: '/teacher/students/'
      preLoaderRoute: typeof TeacherStudentsIndexRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/resources/': {
      id: '/teacher/resources/'
      path: '/resources'
      fullPath: '/teacher/resources/'
      preLoaderRoute: typeof TeacherResourcesIndexRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/quizzes/': {
      id: '/teacher/quizzes/'
      path: '/quizzes'
      fullPath: '/teacher/quizzes/'
      preLoaderRoute: typeof TeacherQuizzesIndexRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/performance/': {
      id: '/teacher/performance/'
      path: '/performance'
      fullPath: '/teacher/performance/'
      preLoaderRoute: typeof TeacherPerformanceIndexRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/lessons/': {
      id: '/teacher/lessons/'
      path: '/lessons'
      fullPath: '/teacher/lessons/'
      preLoaderRoute: typeof TeacherLessonsIndexRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/curriculum/': {
      id: '/teacher/curriculum/'
      path: '/curriculum'
      fullPath: '/teacher/curriculum/'
      preLoaderRoute: typeof TeacherCurriculumIndexRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/classes/': {
      id: '/teacher/classes/'
      path: '/classes'
      fullPath: '/teacher/classes/'
      preLoaderRoute: typeof TeacherClassesIndexRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/assignments/': {
      id: '/teacher/assignments/'
      path: '/assignments'
      fullPath: '/teacher/assignments/'
      preLoaderRoute: typeof TeacherAssignmentsIndexRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/articles/': {
      id: '/teacher/articles/'
      path: '/articles'
      fullPath: '/teacher/articles/'
      preLoaderRoute: typeof TeacherArticlesIndexRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/announcements/': {
      id: '/teacher/announcements/'
      path: '/announcements'
      fullPath: '/teacher/announcements/'
      preLoaderRoute: typeof TeacherAnnouncementsIndexRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/grades/$grade/': {
      id: '/grades/$grade/'
      path: '/grades/$grade'
      fullPath: '/grades/$grade/'
      preLoaderRoute: typeof GradesGradeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teachers/': {
      id: '/admin/teachers/'
      path: '/teachers'
      fullPath: '/admin/teachers/'
      preLoaderRoute: typeof AdminTeachersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/quiz-submissions/': {
      id: '/admin/quiz-submissions/'
      path: '/quiz-submissions'
      fullPath: '/admin/quiz-submissions/'
      preLoaderRoute: typeof AdminQuizSubmissionsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/lessons/': {
      id: '/admin/lessons/'
      path: '/lessons'
      fullPath: '/admin/lessons/'
      preLoaderRoute: typeof AdminLessonsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/assignments/': {
      id: '/admin/assignments/'
      path: '/assignments'
      fullPath: '/admin/assignments/'
      preLoaderRoute: typeof AdminAssignmentsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics/': {
      id: '/admin/analytics/'
      path: '/analytics'
      fullPath: '/admin/analytics/'
      preLoaderRoute: typeof AdminAnalyticsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/teacher/weekly-planning/new': {
      id: '/teacher/weekly-planning/new'
      path: '/weekly-planning/new'
      fullPath: '/teacher/weekly-planning/new'
      preLoaderRoute: typeof TeacherWeeklyPlanningNewRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/weekly-planning/$planId': {
      id: '/teacher/weekly-planning/$planId'
      path: '/weekly-planning/$planId'
      fullPath: '/teacher/weekly-planning/$planId'
      preLoaderRoute: typeof TeacherWeeklyPlanningPlanIdRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/videos/new': {
      id: '/teacher/videos/new'
      path: '/videos/new'
      fullPath: '/teacher/videos/new'
      preLoaderRoute: typeof TeacherVideosNewRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/students/$studentId': {
      id: '/teacher/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/teacher/students/$studentId'
      preLoaderRoute: typeof TeacherStudentsStudentIdRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/resources/new': {
      id: '/teacher/resources/new'
      path: '/resources/new'
      fullPath: '/teacher/resources/new'
      preLoaderRoute: typeof TeacherResourcesNewRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/lessons/new': {
      id: '/teacher/lessons/new'
      path: '/lessons/new'
      fullPath: '/teacher/lessons/new'
      preLoaderRoute: typeof TeacherLessonsNewRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/articles/new': {
      id: '/teacher/articles/new'
      path: '/articles/new'
      fullPath: '/teacher/articles/new'
      preLoaderRoute: typeof TeacherArticlesNewRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/announcements/new': {
      id: '/teacher/announcements/new'
      path: '/announcements/new'
      fullPath: '/teacher/announcements/new'
      preLoaderRoute: typeof TeacherAnnouncementsNewRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/grades/$grade/$lesson': {
      id: '/grades/$grade/$lesson'
      path: '/grades/$grade/$lesson'
      fullPath: '/grades/$grade/$lesson'
      preLoaderRoute: typeof GradesGradeLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/weekly-planning/$planId/': {
      id: '/teacher/weekly-planning/$planId/'
      path: '/'
      fullPath: '/teacher/weekly-planning/$planId/'
      preLoaderRoute: typeof TeacherWeeklyPlanningPlanIdIndexRouteImport
      parentRoute: typeof TeacherWeeklyPlanningPlanIdRoute
    }
    '/teacher/quizzes/manage/': {
      id: '/teacher/quizzes/manage/'
      path: '/quizzes/manage'
      fullPath: '/teacher/quizzes/manage/'
      preLoaderRoute: typeof TeacherQuizzesManageIndexRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/assignments/submissions/': {
      id: '/teacher/assignments/submissions/'
      path: '/assignments/submissions'
      fullPath: '/teacher/assignments/submissions/'
      preLoaderRoute: typeof TeacherAssignmentsSubmissionsIndexRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/weekly-planning/$planId/print': {
      id: '/teacher/weekly-planning/$planId/print'
      path: '/print'
      fullPath: '/teacher/weekly-planning/$planId/print'
      preLoaderRoute: typeof TeacherWeeklyPlanningPlanIdPrintRouteImport
      parentRoute: typeof TeacherWeeklyPlanningPlanIdRoute
    }
    '/teacher/weekly-planning/$planId/edit': {
      id: '/teacher/weekly-planning/$planId/edit'
      path: '/edit'
      fullPath: '/teacher/weekly-planning/$planId/edit'
      preLoaderRoute: typeof TeacherWeeklyPlanningPlanIdEditRouteImport
      parentRoute: typeof TeacherWeeklyPlanningPlanIdRoute
    }
    '/teacher/lessons/edit/$lessonId': {
      id: '/teacher/lessons/edit/$lessonId'
      path: '/lessons/edit/$lessonId'
      fullPath: '/teacher/lessons/edit/$lessonId'
      preLoaderRoute: typeof TeacherLessonsEditLessonIdRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/grades/$grade/units/$unit': {
      id: '/grades/$grade/units/$unit'
      path: '/grades/$grade/units/$unit'
      fullPath: '/grades/$grade/units/$unit'
      preLoaderRoute: typeof GradesGradeUnitsUnitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/lessons/edit/$lessonId': {
      id: '/admin/lessons/edit/$lessonId'
      path: '/lessons/edit/$lessonId'
      fullPath: '/admin/lessons/edit/$lessonId'
      preLoaderRoute: typeof AdminLessonsEditLessonIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminUploadTestRoute: typeof AdminUploadTestRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAnalyticsIndexRoute: typeof AdminAnalyticsIndexRoute
  AdminAssignmentsIndexRoute: typeof AdminAssignmentsIndexRoute
  AdminLessonsIndexRoute: typeof AdminLessonsIndexRoute
  AdminQuizSubmissionsIndexRoute: typeof AdminQuizSubmissionsIndexRoute
  AdminTeachersIndexRoute: typeof AdminTeachersIndexRoute
  AdminLessonsEditLessonIdRoute: typeof AdminLessonsEditLessonIdRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminUploadTestRoute: AdminUploadTestRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAnalyticsIndexRoute: AdminAnalyticsIndexRoute,
  AdminAssignmentsIndexRoute: AdminAssignmentsIndexRoute,
  AdminLessonsIndexRoute: AdminLessonsIndexRoute,
  AdminQuizSubmissionsIndexRoute: AdminQuizSubmissionsIndexRoute,
  AdminTeachersIndexRoute: AdminTeachersIndexRoute,
  AdminLessonsEditLessonIdRoute: AdminLessonsEditLessonIdRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface TeacherWeeklyPlanningPlanIdRouteChildren {
  TeacherWeeklyPlanningPlanIdEditRoute: typeof TeacherWeeklyPlanningPlanIdEditRoute
  TeacherWeeklyPlanningPlanIdPrintRoute: typeof TeacherWeeklyPlanningPlanIdPrintRoute
  TeacherWeeklyPlanningPlanIdIndexRoute: typeof TeacherWeeklyPlanningPlanIdIndexRoute
}

const TeacherWeeklyPlanningPlanIdRouteChildren: TeacherWeeklyPlanningPlanIdRouteChildren =
  {
    TeacherWeeklyPlanningPlanIdEditRoute: TeacherWeeklyPlanningPlanIdEditRoute,
    TeacherWeeklyPlanningPlanIdPrintRoute:
      TeacherWeeklyPlanningPlanIdPrintRoute,
    TeacherWeeklyPlanningPlanIdIndexRoute:
      TeacherWeeklyPlanningPlanIdIndexRoute,
  }

const TeacherWeeklyPlanningPlanIdRouteWithChildren =
  TeacherWeeklyPlanningPlanIdRoute._addFileChildren(
    TeacherWeeklyPlanningPlanIdRouteChildren,
  )

interface TeacherRouteRouteChildren {
  TeacherIndexRoute: typeof TeacherIndexRoute
  TeacherAnnouncementsNewRoute: typeof TeacherAnnouncementsNewRoute
  TeacherArticlesNewRoute: typeof TeacherArticlesNewRoute
  TeacherLessonsNewRoute: typeof TeacherLessonsNewRoute
  TeacherResourcesNewRoute: typeof TeacherResourcesNewRoute
  TeacherStudentsStudentIdRoute: typeof TeacherStudentsStudentIdRoute
  TeacherVideosNewRoute: typeof TeacherVideosNewRoute
  TeacherWeeklyPlanningPlanIdRoute: typeof TeacherWeeklyPlanningPlanIdRouteWithChildren
  TeacherWeeklyPlanningNewRoute: typeof TeacherWeeklyPlanningNewRoute
  TeacherAnnouncementsIndexRoute: typeof TeacherAnnouncementsIndexRoute
  TeacherArticlesIndexRoute: typeof TeacherArticlesIndexRoute
  TeacherAssignmentsIndexRoute: typeof TeacherAssignmentsIndexRoute
  TeacherClassesIndexRoute: typeof TeacherClassesIndexRoute
  TeacherCurriculumIndexRoute: typeof TeacherCurriculumIndexRoute
  TeacherLessonsIndexRoute: typeof TeacherLessonsIndexRoute
  TeacherPerformanceIndexRoute: typeof TeacherPerformanceIndexRoute
  TeacherQuizzesIndexRoute: typeof TeacherQuizzesIndexRoute
  TeacherResourcesIndexRoute: typeof TeacherResourcesIndexRoute
  TeacherStudentsIndexRoute: typeof TeacherStudentsIndexRoute
  TeacherUnitsIndexRoute: typeof TeacherUnitsIndexRoute
  TeacherUsersIndexRoute: typeof TeacherUsersIndexRoute
  TeacherVideosIndexRoute: typeof TeacherVideosIndexRoute
  TeacherWeeklyPlanningIndexRoute: typeof TeacherWeeklyPlanningIndexRoute
  TeacherLessonsEditLessonIdRoute: typeof TeacherLessonsEditLessonIdRoute
  TeacherAssignmentsSubmissionsIndexRoute: typeof TeacherAssignmentsSubmissionsIndexRoute
  TeacherQuizzesManageIndexRoute: typeof TeacherQuizzesManageIndexRoute
}

const TeacherRouteRouteChildren: TeacherRouteRouteChildren = {
  TeacherIndexRoute: TeacherIndexRoute,
  TeacherAnnouncementsNewRoute: TeacherAnnouncementsNewRoute,
  TeacherArticlesNewRoute: TeacherArticlesNewRoute,
  TeacherLessonsNewRoute: TeacherLessonsNewRoute,
  TeacherResourcesNewRoute: TeacherResourcesNewRoute,
  TeacherStudentsStudentIdRoute: TeacherStudentsStudentIdRoute,
  TeacherVideosNewRoute: TeacherVideosNewRoute,
  TeacherWeeklyPlanningPlanIdRoute:
    TeacherWeeklyPlanningPlanIdRouteWithChildren,
  TeacherWeeklyPlanningNewRoute: TeacherWeeklyPlanningNewRoute,
  TeacherAnnouncementsIndexRoute: TeacherAnnouncementsIndexRoute,
  TeacherArticlesIndexRoute: TeacherArticlesIndexRoute,
  TeacherAssignmentsIndexRoute: TeacherAssignmentsIndexRoute,
  TeacherClassesIndexRoute: TeacherClassesIndexRoute,
  TeacherCurriculumIndexRoute: TeacherCurriculumIndexRoute,
  TeacherLessonsIndexRoute: TeacherLessonsIndexRoute,
  TeacherPerformanceIndexRoute: TeacherPerformanceIndexRoute,
  TeacherQuizzesIndexRoute: TeacherQuizzesIndexRoute,
  TeacherResourcesIndexRoute: TeacherResourcesIndexRoute,
  TeacherStudentsIndexRoute: TeacherStudentsIndexRoute,
  TeacherUnitsIndexRoute: TeacherUnitsIndexRoute,
  TeacherUsersIndexRoute: TeacherUsersIndexRoute,
  TeacherVideosIndexRoute: TeacherVideosIndexRoute,
  TeacherWeeklyPlanningIndexRoute: TeacherWeeklyPlanningIndexRoute,
  TeacherLessonsEditLessonIdRoute: TeacherLessonsEditLessonIdRoute,
  TeacherAssignmentsSubmissionsIndexRoute:
    TeacherAssignmentsSubmissionsIndexRoute,
  TeacherQuizzesManageIndexRoute: TeacherQuizzesManageIndexRoute,
}

const TeacherRouteRouteWithChildren = TeacherRouteRoute._addFileChildren(
  TeacherRouteRouteChildren,
)

interface StudentRouteChildren {
  StudentProfileRoute: typeof StudentProfileRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentProfileRoute: StudentProfileRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  TeacherRouteRoute: TeacherRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminLoginRoute: AdminLoginRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  HallOfFameRoute: HallOfFameRoute,
  ResourceLibraryRoute: ResourceLibraryRoute,
  ResourcesRoute: ResourcesRoute,
  StudentRoute: StudentRouteWithChildren,
  StudentDashboardRoute: StudentDashboardRoute,
  VideoLessonsRoute: VideoLessonsRoute,
  AnnouncementsSlugRoute: AnnouncementsSlugRoute,
  AssignmentsAssignmentIdRoute: AssignmentsAssignmentIdRoute,
  CategoriesCategoryRoute: CategoriesCategoryRoute,
  ParentSlugRoute: ParentSlugRoute,
  ParentDashboardRoute: ParentDashboardRoute,
  ParentSettingsRoute: ParentSettingsRoute,
  QuizzesSlugRoute: QuizzesSlugRoute,
  VideosSlugRoute: VideosSlugRoute,
  AnnouncementsIndexRoute: AnnouncementsIndexRoute,
  AssignmentsIndexRoute: AssignmentsIndexRoute,
  GradesIndexRoute: GradesIndexRoute,
  ParentIndexRoute: ParentIndexRoute,
  QuizzesIndexRoute: QuizzesIndexRoute,
  VideosIndexRoute: VideosIndexRoute,
  GradesGradeLessonRoute: GradesGradeLessonRoute,
  GradesGradeIndexRoute: GradesGradeIndexRoute,
  GradesGradeUnitsUnitRoute: GradesGradeUnitsUnitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
